import { Sunburst } from '@ant-design/charts';
import { Radar } from '@ant-design/plots';
import React, { useEffect, useRef, useState } from 'react';
const getArea = (
	data: {
		area: string;
		province: string;
		month: string;
		value: number;
	}[],
	key: string,
	exclude?: string,
	excludeKey?: string
) => {
	let newData: {
		area: string;
		province: string;
		month: string;
		value: number;
	}[] = [];
	if (exclude && excludeKey)
		data = data.filter((item) => item[excludeKey] == exclude);
	data.forEach((item) => {
		let it = newData.find((i) => i[key] == item[key] && i.month == item.month);
		if (it) {
			it.value += item.value;
		} else {
			newData.push(item);
		}
	});
	return newData;
};
const DemoSunburst = ({
	setArea,
}: {
	setArea: React.Dispatch<React.SetStateAction<string>>;
}) => {
	const [data, setData] = useState({
		name: 'root',
		children: [
			{
				name: '南方区域',
				children: [
					{
						name: '上海',
						children: [
							{
								province: '上海',
								name: '上海市',
								area: '南方区域',
								value: 163,
							},
						],
					},
					{
						name: '云南',
						children: [
							{
								province: '云南',
								name: '临沧市',
								area: '南方区域',
								value: 73,
							},
							{
								province: '云南',
								name: '丽江市',
								area: '南方区域',
								value: 37,
							},
							{
								province: '云南',
								name: '保山市',
								area: '南方区域',
								value: 69,
							},
							{
								province: '云南',
								name: '大理白族自治州',
								area: '南方区域',
								value: 53,
							},
							{
								province: '云南',
								name: '德宏傣族景颇族自治州',
								area: '南方区域',
								value: 79,
							},
							{
								province: '云南',
								name: '怒江傈僳族自治州',
								area: '南方区域',
								value: 32,
							},
							{
								province: '云南',
								name: '文山壮族苗族自治州',
								area: '南方区域',
								value: 101,
							},
							{
								province: '云南',
								name: '昆明市',
								area: '南方区域',
								value: 76,
							},
							{
								province: '云南',
								name: '昭通市',
								area: '南方区域',
								value: 120,
							},
							{
								province: '云南',
								name: '普洱市',
								area: '南方区域',
								value: 73,
							},
							{
								province: '云南',
								name: '曲靖市',
								area: '南方区域',
								value: 72,
							},
							{
								province: '云南',
								name: '楚雄彝族自治州',
								area: '南方区域',
								value: 71,
							},
							{
								province: '云南',
								name: '玉溪市',
								area: '南方区域',
								value: 75,
							},
							{
								province: '云南',
								name: '红河哈尼族彝族自治州',
								area: '南方区域',
								value: 84,
							},
							{
								province: '云南',
								name: '西双版纳傣族自治州',
								area: '南方区域',
								value: 81,
							},
							{
								province: '云南',
								name: '迪庆藏族自治州',
								area: '南方区域',
								value: 22,
							},
						],
					},
					{
						name: '台湾',
						children: [
							{
								province: '台湾',
								name: '台湾省',
								area: '南方区域',
								value: 66,
							},
						],
					},
					{
						name: '四川',
						children: [
							{
								province: '四川',
								name: '乐山市',
								area: '南方区域',
								value: 154,
							},
							{
								province: '四川',
								name: '内江市',
								area: '南方区域',
								value: 160,
							},
							{
								province: '四川',
								name: '凉山彝族自治州',
								area: '南方区域',
								value: 63,
							},
							{
								province: '四川',
								name: '南充市',
								area: '南方区域',
								value: 155,
							},
							{
								province: '四川',
								name: '宜宾市',
								area: '南方区域',
								value: 158,
							},
							{
								province: '四川',
								name: '巴中市',
								area: '南方区域',
								value: 152,
							},
							{
								province: '四川',
								name: '广元市',
								area: '南方区域',
								value: 130,
							},
							{
								province: '四川',
								name: '广安市',
								area: '南方区域',
								value: 140,
							},
							{
								province: '四川',
								name: '德阳市',
								area: '南方区域',
								value: 159,
							},
							{
								province: '四川',
								name: '成都市',
								area: '南方区域',
								value: 159,
							},
							{
								province: '四川',
								name: '攀枝花市',
								area: '南方区域',
								value: 80,
							},
							{
								province: '四川',
								name: '泸州市',
								area: '南方区域',
								value: 146,
							},
							{
								province: '四川',
								name: '甘孜藏族自治州',
								area: '南方区域',
								value: 7,
							},
							{
								province: '四川',
								name: '眉山市',
								area: '南方区域',
								value: 159,
							},
							{
								province: '四川',
								name: '绵阳市',
								area: '南方区域',
								value: 122,
							},
							{
								province: '四川',
								name: '自贡市',
								area: '南方区域',
								value: 163,
							},
							{
								province: '四川',
								name: '资阳市',
								area: '南方区域',
								value: 158,
							},
							{
								province: '四川',
								name: '达州市',
								area: '南方区域',
								value: 153,
							},
							{
								province: '四川',
								name: '遂宁市',
								area: '南方区域',
								value: 155,
							},
							{
								province: '四川',
								name: '阿坝藏族羌族自治州',
								area: '南方区域',
								value: 18,
							},
							{
								province: '四川',
								name: '雅安市',
								area: '南方区域',
								value: 95,
							},
						],
					},
					{
						name: '安徽',
						children: [
							{
								province: '安徽',
								name: '亳州市',
								area: '南方区域',
								value: 228,
							},
							{
								province: '安徽',
								name: '六安市',
								area: '南方区域',
								value: 189,
							},
							{
								province: '安徽',
								name: '合肥市',
								area: '南方区域',
								value: 195,
							},
							{
								province: '安徽',
								name: '安庆市',
								area: '南方区域',
								value: 173,
							},
							{
								province: '安徽',
								name: '宣城市',
								area: '南方区域',
								value: 161,
							},
							{
								province: '安徽',
								name: '宿州市',
								area: '南方区域',
								value: 199,
							},
							{
								province: '安徽',
								name: '池州市',
								area: '南方区域',
								value: 160,
							},
							{
								province: '安徽',
								name: '淮北市',
								area: '南方区域',
								value: 218,
							},
							{
								province: '安徽',
								name: '淮南市',
								area: '南方区域',
								value: 216,
							},
							{
								province: '安徽',
								name: '滁州市',
								area: '南方区域',
								value: 205,
							},
							{
								province: '安徽',
								name: '芜湖市',
								area: '南方区域',
								value: 188,
							},
							{
								province: '安徽',
								name: '蚌埠市',
								area: '南方区域',
								value: 203,
							},
							{
								province: '安徽',
								name: '铜陵市',
								area: '南方区域',
								value: 183,
							},
							{
								province: '安徽',
								name: '阜阳市',
								area: '南方区域',
								value: 244,
							},
							{
								province: '安徽',
								name: '马鞍山市',
								area: '南方区域',
								value: 191,
							},
							{
								province: '安徽',
								name: '黄山市',
								area: '南方区域',
								value: 123,
							},
						],
					},
					{
						name: '广东',
						children: [
							{
								province: '广东',
								name: '东莞市',
								area: '南方区域',
								value: 128,
							},
							{
								province: '广东',
								name: '中山市',
								area: '南方区域',
								value: 113,
							},
							{
								province: '广东',
								name: '云浮市',
								area: '南方区域',
								value: 145,
							},
							{
								province: '广东',
								name: '佛山市',
								area: '南方区域',
								value: 152,
							},
							{
								province: '广东',
								name: '广州市',
								area: '南方区域',
								value: 128,
							},
							{
								province: '广东',
								name: '惠州市',
								area: '南方区域',
								value: 104,
							},
							{
								province: '广东',
								name: '揭阳市',
								area: '南方区域',
								value: 123,
							},
							{
								province: '广东',
								name: '梅州市',
								area: '南方区域',
								value: 98,
							},
							{
								province: '广东',
								name: '汕头市',
								area: '南方区域',
								value: 97,
							},
							{
								province: '广东',
								name: '汕尾市',
								area: '南方区域',
								value: 110,
							},
							{
								province: '广东',
								name: '江门市',
								area: '南方区域',
								value: 129,
							},
							{
								province: '广东',
								name: '河源市',
								area: '南方区域',
								value: 105,
							},
							{
								province: '广东',
								name: '深圳市',
								area: '南方区域',
								value: 102,
							},
							{
								province: '广东',
								name: '清远市',
								area: '南方区域',
								value: 118,
							},
							{
								province: '广东',
								name: '湛江市',
								area: '南方区域',
								value: 102,
							},
							{
								province: '广东',
								name: '潮州市',
								area: '南方区域',
								value: 95,
							},
							{
								province: '广东',
								name: '珠海市',
								area: '南方区域',
								value: 97,
							},
							{
								province: '广东',
								name: '肇庆市',
								area: '南方区域',
								value: 134,
							},
							{
								province: '广东',
								name: '茂名市',
								area: '南方区域',
								value: 120,
							},
							{
								province: '广东',
								name: '阳江市',
								area: '南方区域',
								value: 136,
							},
							{
								province: '广东',
								name: '韶关市',
								area: '南方区域',
								value: 112,
							},
						],
					},
					{
						name: '广西',
						children: [
							{
								province: '广西',
								name: '北海市',
								area: '南方区域',
								value: 129,
							},
							{
								province: '广西',
								name: '南宁市',
								area: '南方区域',
								value: 154,
							},
							{
								province: '广西',
								name: '崇左市',
								area: '南方区域',
								value: 147,
							},
							{
								province: '广西',
								name: '来宾市',
								area: '南方区域',
								value: 147,
							},
							{
								province: '广西',
								name: '柳州市',
								area: '南方区域',
								value: 137,
							},
							{
								province: '广西',
								name: '桂林市',
								area: '南方区域',
								value: 140,
							},
							{
								province: '广西',
								name: '梧州市',
								area: '南方区域',
								value: 134,
							},
							{
								province: '广西',
								name: '河池市',
								area: '南方区域',
								value: 142,
							},
							{
								province: '广西',
								name: '玉林市',
								area: '南方区域',
								value: 138,
							},
							{
								province: '广西',
								name: '百色市',
								area: '南方区域',
								value: 130,
							},
							{
								province: '广西',
								name: '贵港市',
								area: '南方区域',
								value: 150,
							},
							{
								province: '广西',
								name: '贺州市',
								area: '南方区域',
								value: 126,
							},
							{
								province: '广西',
								name: '钦州市',
								area: '南方区域',
								value: 136,
							},
							{
								province: '广西',
								name: '防城港市',
								area: '南方区域',
								value: 135,
							},
						],
					},
					{
						name: '江苏',
						children: [
							{
								province: '江苏',
								name: '南京市',
								area: '南方区域',
								value: 197,
							},
							{
								province: '江苏',
								name: '南通市',
								area: '南方区域',
								value: 187,
							},
							{
								province: '江苏',
								name: '宿迁市',
								area: '南方区域',
								value: 183,
							},
							{
								province: '江苏',
								name: '常州市',
								area: '南方区域',
								value: 193,
							},
							{
								province: '江苏',
								name: '徐州市',
								area: '南方区域',
								value: 190,
							},
							{
								province: '江苏',
								name: '扬州市',
								area: '南方区域',
								value: 218,
							},
							{
								province: '江苏',
								name: '无锡市',
								area: '南方区域',
								value: 190,
							},
							{
								province: '江苏',
								name: '泰州市',
								area: '南方区域',
								value: 212,
							},
							{
								province: '江苏',
								name: '淮安市',
								area: '南方区域',
								value: 195,
							},
							{
								province: '江苏',
								name: '盐城市',
								area: '南方区域',
								value: 189,
							},
							{
								province: '江苏',
								name: '苏州市',
								area: '南方区域',
								value: 176,
							},
							{
								province: '江苏',
								name: '连云港市',
								area: '南方区域',
								value: 166,
							},
							{
								province: '江苏',
								name: '镇江市',
								area: '南方区域',
								value: 207,
							},
						],
					},
					{
						name: '江西',
						children: [
							{
								province: '江西',
								name: '上饶市',
								area: '南方区域',
								value: 127,
							},
							{
								province: '江西',
								name: '九江市',
								area: '南方区域',
								value: 153,
							},
							{
								province: '江西',
								name: '南昌市',
								area: '南方区域',
								value: 135,
							},
							{
								province: '江西',
								name: '吉安市',
								area: '南方区域',
								value: 124,
							},
							{
								province: '江西',
								name: '宜春市',
								area: '南方区域',
								value: 138,
							},
							{
								province: '江西',
								name: '抚州市',
								area: '南方区域',
								value: 103,
							},
							{
								province: '江西',
								name: '新余市',
								area: '南方区域',
								value: 150,
							},
							{
								province: '江西',
								name: '景德镇市',
								area: '南方区域',
								value: 123,
							},
							{
								province: '江西',
								name: '萍乡市',
								area: '南方区域',
								value: 135,
							},
							{
								province: '江西',
								name: '赣州市',
								area: '南方区域',
								value: 102,
							},
							{
								province: '江西',
								name: '鹰潭市',
								area: '南方区域',
								value: 119,
							},
						],
					},
					{
						name: '浙江',
						children: [
							{
								province: '浙江',
								name: '丽水市',
								area: '南方区域',
								value: 104,
							},
							{
								province: '浙江',
								name: '台州市',
								area: '南方区域',
								value: 124,
							},
							{
								province: '浙江',
								name: '嘉兴市',
								area: '南方区域',
								value: 158,
							},
							{
								province: '浙江',
								name: '宁波市',
								area: '南方区域',
								value: 137,
							},
							{
								province: '浙江',
								name: '杭州市',
								area: '南方区域',
								value: 152,
							},
							{
								province: '浙江',
								name: '温州市',
								area: '南方区域',
								value: 114,
							},
							{
								province: '浙江',
								name: '湖州市',
								area: '南方区域',
								value: 164,
							},
							{
								province: '浙江',
								name: '绍兴市',
								area: '南方区域',
								value: 153,
							},
							{
								province: '浙江',
								name: '舟山市',
								area: '南方区域',
								value: 94,
							},
							{
								province: '浙江',
								name: '衢州市',
								area: '南方区域',
								value: 122,
							},
							{
								province: '浙江',
								name: '金华市',
								area: '南方区域',
								value: 132,
							},
						],
					},
					{
						name: '海南',
						children: [
							{
								province: '海南',
								name: '万宁市',
								area: '南方区域',
								value: 69,
							},
							{
								province: '海南',
								name: '三亚市',
								area: '南方区域',
								value: 56,
							},
							{
								province: '海南',
								name: '东方市',
								area: '南方区域',
								value: 72,
							},
							{
								province: '海南',
								name: '临高县',
								area: '南方区域',
								value: 79,
							},
							{
								province: '海南',
								name: '乐东黎族自治县',
								area: '南方区域',
								value: 64,
							},
							{
								province: '海南',
								name: '五指山市',
								area: '南方区域',
								value: 71,
							},
							{
								province: '海南',
								name: '儋州市',
								area: '南方区域',
								value: 83,
							},
							{
								province: '海南',
								name: '定安县',
								area: '南方区域',
								value: 71,
							},
							{
								province: '海南',
								name: '屯昌县',
								area: '南方区域',
								value: 74,
							},
							{
								province: '海南',
								name: '文昌市',
								area: '南方区域',
								value: 67,
							},
							{
								province: '海南',
								name: '昌江黎族自治县',
								area: '南方区域',
								value: 79,
							},
							{
								province: '海南',
								name: '海口市',
								area: '南方区域',
								value: 70,
							},
							{
								province: '海南',
								name: '澄迈县',
								area: '南方区域',
								value: 76,
							},
							{
								province: '海南',
								name: '琼中黎族苗族自治县',
								area: '南方区域',
								value: 78,
							},
							{
								province: '海南',
								name: '琼海市',
								area: '南方区域',
								value: 66,
							},
							{
								province: '海南',
								name: '白沙黎族自治县',
								area: '南方区域',
								value: 80,
							},
							{
								province: '海南',
								name: '陵水黎族自治县',
								area: '南方区域',
								value: 64,
							},
						],
					},
					{
						name: '湖北',
						children: [
							{
								province: '湖北',
								name: '仙桃市',
								area: '南方区域',
								value: 191,
							},
							{
								province: '湖北',
								name: '十堰市',
								area: '南方区域',
								value: 173,
							},
							{
								province: '湖北',
								name: '咸宁市',
								area: '南方区域',
								value: 160,
							},
							{
								province: '湖北',
								name: '天门市',
								area: '南方区域',
								value: 197,
							},
							{
								province: '湖北',
								name: '孝感市',
								area: '南方区域',
								value: 198,
							},
							{
								province: '湖北',
								name: '宜昌市',
								area: '南方区域',
								value: 177,
							},
							{
								province: '湖北',
								name: '恩施土家族苗族自治州',
								area: '南方区域',
								value: 158,
							},
							{
								province: '湖北',
								name: '武汉市',
								area: '南方区域',
								value: 186,
							},
							{
								province: '湖北',
								name: '潜江市',
								area: '南方区域',
								value: 195,
							},
							{
								province: '湖北',
								name: '神农架林区',
								area: '南方区域',
								value: 155,
							},
							{
								province: '湖北',
								name: '荆州市',
								area: '南方区域',
								value: 188,
							},
							{
								province: '湖北',
								name: '荆门市',
								area: '南方区域',
								value: 211,
							},
							{
								province: '湖北',
								name: '襄阳市',
								area: '南方区域',
								value: 202,
							},
							{
								province: '湖北',
								name: '鄂州市',
								area: '南方区域',
								value: 170,
							},
							{
								province: '湖北',
								name: '随州市',
								area: '南方区域',
								value: 213,
							},
							{
								province: '湖北',
								name: '黄冈市',
								area: '南方区域',
								value: 173,
							},
							{
								province: '湖北',
								name: '黄石市',
								area: '南方区域',
								value: 160,
							},
						],
					},
					{
						name: '湖南',
						children: [
							{
								province: '湖南',
								name: '娄底市',
								area: '南方区域',
								value: 155,
							},
							{
								province: '湖南',
								name: '岳阳市',
								area: '南方区域',
								value: 164,
							},
							{
								province: '湖南',
								name: '常德市',
								area: '南方区域',
								value: 171,
							},
							{
								province: '湖南',
								name: '张家界市',
								area: '南方区域',
								value: 156,
							},
							{
								province: '湖南',
								name: '怀化市',
								area: '南方区域',
								value: 151,
							},
							{
								province: '湖南',
								name: '株洲市',
								area: '南方区域',
								value: 141,
							},
							{
								province: '湖南',
								name: '永州市',
								area: '南方区域',
								value: 142,
							},
							{
								province: '湖南',
								name: '湘潭市',
								area: '南方区域',
								value: 162,
							},
							{
								province: '湖南',
								name: '湘西土家族苗族自治州',
								area: '南方区域',
								value: 147,
							},
							{
								province: '湖南',
								name: '益阳市',
								area: '南方区域',
								value: 163,
							},
							{
								province: '湖南',
								name: '衡阳市',
								area: '南方区域',
								value: 156,
							},
							{
								province: '湖南',
								name: '邵阳市',
								area: '南方区域',
								value: 156,
							},
							{
								province: '湖南',
								name: '郴州市',
								area: '南方区域',
								value: 111,
							},
							{
								province: '湖南',
								name: '长沙市',
								area: '南方区域',
								value: 161,
							},
						],
					},
					{
						name: '福建',
						children: [
							{
								province: '福建',
								name: '三明市',
								area: '南方区域',
								value: 84,
							},
							{
								province: '福建',
								name: '南平市',
								area: '南方区域',
								value: 84,
							},
							{
								province: '福建',
								name: '厦门市',
								area: '南方区域',
								value: 86,
							},
							{
								province: '福建',
								name: '宁德市',
								area: '南方区域',
								value: 85,
							},
							{
								province: '福建',
								name: '泉州市',
								area: '南方区域',
								value: 83,
							},
							{
								province: '福建',
								name: '漳州市',
								area: '南方区域',
								value: 89,
							},
							{
								province: '福建',
								name: '福州市',
								area: '南方区域',
								value: 81,
							},
							{
								province: '福建',
								name: '莆田市',
								area: '南方区域',
								value: 81,
							},
							{
								province: '福建',
								name: '龙岩市',
								area: '南方区域',
								value: 80,
							},
						],
					},
					{
						name: '贵州',
						children: [
							{
								province: '贵州',
								name: '六盘水市',
								area: '南方区域',
								value: 92,
							},
							{
								province: '贵州',
								name: '安顺市',
								area: '南方区域',
								value: 105,
							},
							{
								province: '贵州',
								name: '毕节市',
								area: '南方区域',
								value: 107,
							},
							{
								province: '贵州',
								name: '贵阳市',
								area: '南方区域',
								value: 125,
							},
							{
								province: '贵州',
								name: '遵义市',
								area: '南方区域',
								value: 135,
							},
							{
								province: '贵州',
								name: '铜仁市',
								area: '南方区域',
								value: 113,
							},
							{
								province: '贵州',
								name: '黔东南苗族侗族自治州',
								area: '南方区域',
								value: 119,
							},
							{
								province: '贵州',
								name: '黔南布依族苗族自治州',
								area: '南方区域',
								value: 121,
							},
							{
								province: '贵州',
								name: '黔西南布依族苗族自治州',
								area: '南方区域',
								value: 84,
							},
						],
					},
					{
						name: '重庆',
						children: [
							{
								province: '重庆',
								name: '重庆城区',
								area: '南方区域',
								value: 153,
							},
							{
								province: '重庆',
								name: '重庆郊县',
								area: '南方区域',
								value: 154,
							},
						],
					},
					{
						name: '陕西',
						children: [
							{
								province: '陕西',
								name: '咸阳市',
								area: '南方区域',
								value: 179,
							},
							{
								province: '陕西',
								name: '商洛市',
								area: '南方区域',
								value: 163,
							},
							{
								province: '陕西',
								name: '安康市',
								area: '南方区域',
								value: 154,
							},
							{
								province: '陕西',
								name: '宝鸡市',
								area: '南方区域',
								value: 158,
							},
							{
								province: '陕西',
								name: '延安市',
								area: '南方区域',
								value: 144,
							},
							{
								province: '陕西',
								name: '榆林市',
								area: '南方区域',
								value: 124,
							},
							{
								province: '陕西',
								name: '汉中市',
								area: '南方区域',
								value: 152,
							},
							{
								province: '陕西',
								name: '渭南市',
								area: '南方区域',
								value: 184,
							},
							{
								province: '陕西',
								name: '西安市',
								area: '南方区域',
								value: 177,
							},
							{
								province: '陕西',
								name: '铜川市',
								area: '南方区域',
								value: 165,
							},
						],
					},
					{
						name: '香港',
						children: [
							{
								province: '香港',
								name: '香港特别行政区',
								area: '南方区域',
								value: 90,
							},
						],
					},
				],
			},
			{
				name: '北方区域',
				children: [
					{
						name: '北京',
						children: [
							{
								province: '北京',
								name: '北京市',
								area: '北方区域',
								value: 153,
							},
						],
					},
					{
						name: '吉林',
						children: [
							{
								province: '吉林',
								name: '吉林市',
								area: '北方区域',
								value: 68,
							},
							{
								province: '吉林',
								name: '四平市',
								area: '北方区域',
								value: 71,
							},
							{
								province: '吉林',
								name: '延边朝鲜族自治州',
								area: '北方区域',
								value: 66,
							},
							{
								province: '吉林',
								name: '松原市',
								area: '北方区域',
								value: 59,
							},
							{
								province: '吉林',
								name: '白城市',
								area: '北方区域',
								value: 51,
							},
							{
								province: '吉林',
								name: '白山市',
								area: '北方区域',
								value: 67,
							},
							{
								province: '吉林',
								name: '辽源市',
								area: '北方区域',
								value: 87,
							},
							{
								province: '吉林',
								name: '通化市',
								area: '北方区域',
								value: 78,
							},
							{
								province: '吉林',
								name: '长春市',
								area: '北方区域',
								value: 67,
							},
						],
					},
					{
						name: '天津',
						children: [
							{
								province: '天津',
								name: '天津市',
								area: '北方区域',
								value: 158,
							},
						],
					},
					{
						name: '山东',
						children: [
							{
								province: '山东',
								name: '东营市',
								area: '北方区域',
								value: 167,
							},
							{
								province: '山东',
								name: '临沂市',
								area: '北方区域',
								value: 175,
							},
							{
								province: '山东',
								name: '威海市',
								area: '北方区域',
								value: 90,
							},
							{
								province: '山东',
								name: '德州市',
								area: '北方区域',
								value: 175,
							},
							{
								province: '山东',
								name: '日照市',
								area: '北方区域',
								value: 163,
							},
							{
								province: '山东',
								name: '枣庄市',
								area: '北方区域',
								value: 186,
							},
							{
								province: '山东',
								name: '泰安市',
								area: '北方区域',
								value: 186,
							},
							{
								province: '山东',
								name: '济南市',
								area: '北方区域',
								value: 185,
							},
							{
								province: '山东',
								name: '济宁市',
								area: '北方区域',
								value: 186,
							},
							{
								province: '山东',
								name: '淄博市',
								area: '北方区域',
								value: 183,
							},
							{
								province: '山东',
								name: '滨州市',
								area: '北方区域',
								value: 170,
							},
							{
								province: '山东',
								name: '潍坊市',
								area: '北方区域',
								value: 169,
							},
							{
								province: '山东',
								name: '烟台市',
								area: '北方区域',
								value: 138,
							},
							{
								province: '山东',
								name: '聊城市',
								area: '北方区域',
								value: 187,
							},
							{
								province: '山东',
								name: '菏泽市',
								area: '北方区域',
								value: 208,
							},
							{
								province: '山东',
								name: '青岛市',
								area: '北方区域',
								value: 153,
							},
						],
					},
					{
						name: '山西',
						children: [
							{
								province: '山西',
								name: '临汾市',
								area: '北方区域',
								value: 181,
							},
							{
								province: '山西',
								name: '吕梁市',
								area: '北方区域',
								value: 159,
							},
							{
								province: '山西',
								name: '大同市',
								area: '北方区域',
								value: 137,
							},
							{
								province: '山西',
								name: '太原市',
								area: '北方区域',
								value: 165,
							},
							{
								province: '山西',
								name: '忻州市',
								area: '北方区域',
								value: 155,
							},
							{
								province: '山西',
								name: '晋中市',
								area: '北方区域',
								value: 170,
							},
							{
								province: '山西',
								name: '晋城市',
								area: '北方区域',
								value: 183,
							},
							{
								province: '山西',
								name: '朔州市',
								area: '北方区域',
								value: 154,
							},
							{
								province: '山西',
								name: '运城市',
								area: '北方区域',
								value: 199,
							},
							{
								province: '山西',
								name: '长治市',
								area: '北方区域',
								value: 174,
							},
							{
								province: '山西',
								name: '阳泉市',
								area: '北方区域',
								value: 169,
							},
						],
					},
					{
						name: '河北',
						children: [
							{
								province: '河北',
								name: '保定市',
								area: '北方区域',
								value: 163,
							},
							{
								province: '河北',
								name: '唐山市',
								area: '北方区域',
								value: 158,
							},
							{
								province: '河北',
								name: '廊坊市',
								area: '北方区域',
								value: 164,
							},
							{
								province: '河北',
								name: '张家口市',
								area: '北方区域',
								value: 79,
							},
							{
								province: '河北',
								name: '承德市',
								area: '北方区域',
								value: 83,
							},
							{
								province: '河北',
								name: '沧州市',
								area: '北方区域',
								value: 163,
							},
							{
								province: '河北',
								name: '石家庄市',
								area: '北方区域',
								value: 174,
							},
							{
								province: '河北',
								name: '秦皇岛市',
								area: '北方区域',
								value: 148,
							},
							{
								province: '河北',
								name: '衡水市',
								area: '北方区域',
								value: 172,
							},
							{
								province: '河北',
								name: '邢台市',
								area: '北方区域',
								value: 177,
							},
							{
								province: '河北',
								name: '邯郸市',
								area: '北方区域',
								value: 182,
							},
						],
					},
					{
						name: '河南',
						children: [
							{
								province: '河南',
								name: '三门峡市',
								area: '北方区域',
								value: 183,
							},
							{
								province: '河南',
								name: '信阳市',
								area: '北方区域',
								value: 228,
							},
							{
								province: '河南',
								name: '南阳市',
								area: '北方区域',
								value: 207,
							},
							{
								province: '河南',
								name: '周口市',
								area: '北方区域',
								value: 247,
							},
							{
								province: '河南',
								name: '商丘市',
								area: '北方区域',
								value: 230,
							},
							{
								province: '河南',
								name: '安阳市',
								area: '北方区域',
								value: 185,
							},
							{
								province: '河南',
								name: '平顶山市',
								area: '北方区域',
								value: 201,
							},
							{
								province: '河南',
								name: '开封市',
								area: '北方区域',
								value: 224,
							},
							{
								province: '河南',
								name: '新乡市',
								area: '北方区域',
								value: 190,
							},
							{
								province: '河南',
								name: '洛阳市',
								area: '北方区域',
								value: 188,
							},
							{
								province: '河南',
								name: '济源市',
								area: '北方区域',
								value: 182,
							},
							{
								province: '河南',
								name: '漯河市',
								area: '北方区域',
								value: 240,
							},
							{
								province: '河南',
								name: '濮阳市',
								area: '北方区域',
								value: 197,
							},
							{
								province: '河南',
								name: '焦作市',
								area: '北方区域',
								value: 188,
							},
							{
								province: '河南',
								name: '许昌市',
								area: '北方区域',
								value: 219,
							},
							{
								province: '河南',
								name: '郑州市',
								area: '北方区域',
								value: 198,
							},
							{
								province: '河南',
								name: '驻马店市',
								area: '北方区域',
								value: 247,
							},
							{
								province: '河南',
								name: '鹤壁市',
								area: '北方区域',
								value: 184,
							},
						],
					},
					{
						name: '辽宁',
						children: [
							{
								province: '辽宁',
								name: '丹东市',
								area: '北方区域',
								value: 90,
							},
							{
								province: '辽宁',
								name: '大连市',
								area: '北方区域',
								value: 108,
							},
							{
								province: '辽宁',
								name: '抚顺市',
								area: '北方区域',
								value: 87,
							},
							{
								province: '辽宁',
								name: '朝阳市',
								area: '北方区域',
								value: 118,
							},
							{
								province: '辽宁',
								name: '本溪市',
								area: '北方区域',
								value: 84,
							},
							{
								province: '辽宁',
								name: '沈阳市',
								area: '北方区域',
								value: 108,
							},
							{
								province: '辽宁',
								name: '盘锦市',
								area: '北方区域',
								value: 130,
							},
							{
								province: '辽宁',
								name: '营口市',
								area: '北方区域',
								value: 108,
							},
							{
								province: '辽宁',
								name: '葫芦岛市',
								area: '北方区域',
								value: 139,
							},
							{
								province: '辽宁',
								name: '辽阳市',
								area: '北方区域',
								value: 104,
							},
							{
								province: '辽宁',
								name: '铁岭市',
								area: '北方区域',
								value: 92,
							},
							{
								province: '辽宁',
								name: '锦州市',
								area: '北方区域',
								value: 136,
							},
							{
								province: '辽宁',
								name: '阜新市',
								area: '北方区域',
								value: 104,
							},
							{
								province: '辽宁',
								name: '鞍山市',
								area: '北方区域',
								value: 102,
							},
						],
					},
					{
						name: '黑龙江',
						children: [
							{
								province: '黑龙江',
								name: '七台河市',
								area: '北方区域',
								value: 67,
							},
							{
								province: '黑龙江',
								name: '伊春市',
								area: '北方区域',
								value: 56,
							},
							{
								province: '黑龙江',
								name: '佳木斯市',
								area: '北方区域',
								value: 58,
							},
							{
								province: '黑龙江',
								name: '双鸭山市',
								area: '北方区域',
								value: 57,
							},
							{
								province: '黑龙江',
								name: '哈尔滨市',
								area: '北方区域',
								value: 74,
							},
							{
								province: '黑龙江',
								name: '大兴安岭地区',
								area: '北方区域',
								value: 9,
							},
							{
								province: '黑龙江',
								name: '大庆市',
								area: '北方区域',
								value: 59,
							},
							{
								province: '黑龙江',
								name: '牡丹江市',
								area: '北方区域',
								value: 74,
							},
							{
								province: '黑龙江',
								name: '绥化市',
								area: '北方区域',
								value: 75,
							},
							{
								province: '黑龙江',
								name: '鸡西市',
								area: '北方区域',
								value: 62,
							},
							{
								province: '黑龙江',
								name: '鹤岗市',
								area: '北方区域',
								value: 57,
							},
							{
								province: '黑龙江',
								name: '黑河市',
								area: '北方区域',
								value: 64,
							},
							{
								province: '黑龙江',
								name: '齐齐哈尔市',
								area: '北方区域',
								value: 60,
							},
						],
					},
				],
			},
			{
				name: '西北地区',
				children: [
					{
						name: '宁夏',
						children: [
							{
								province: '宁夏',
								name: '中卫市',
								area: '西北地区',
								value: 124,
							},
							{
								province: '宁夏',
								name: '吴忠市',
								area: '西北地区',
								value: 113,
							},
							{
								province: '宁夏',
								name: '固原市',
								area: '西北地区',
								value: 117,
							},
							{
								province: '宁夏',
								name: '石嘴山市',
								area: '西北地区',
								value: 145,
							},
							{
								province: '宁夏',
								name: '银川市',
								area: '西北地区',
								value: 151,
							},
						],
					},
					{
						name: '新疆',
						children: [
							{
								province: '新疆',
								name: '乌鲁木齐市',
								area: '西北地区',
								value: 83,
							},
							{
								province: '新疆',
								name: '五家渠市',
								area: '西北地区',
								value: 130,
							},
							{
								province: '新疆',
								name: '伊犁哈萨克自治州',
								area: '西北地区',
								value: 58,
							},
							{
								province: '新疆',
								name: '克孜勒苏柯尔克孜自治州',
								area: '西北地区',
								value: 26,
							},
							{
								province: '新疆',
								name: '克拉玛依市',
								area: '西北地区',
								value: 72,
							},
							{
								province: '新疆',
								name: '北屯市',
								area: '西北地区',
								value: 18,
							},
							{
								province: '新疆',
								name: '博尔塔拉蒙古自治州',
								area: '西北地区',
								value: 64,
							},
							{
								province: '新疆',
								name: '双河市',
								area: '西北地区',
								value: 96,
							},
							{
								province: '新疆',
								name: '可克达拉市',
								area: '西北地区',
								value: 155,
							},
							{
								province: '新疆',
								name: '和田地区',
								area: '西北地区',
								value: 29,
							},
							{
								province: '新疆',
								name: '哈密市',
								area: '西北地区',
								value: 25,
							},
							{
								province: '新疆',
								name: '喀什地区',
								area: '西北地区',
								value: 71,
							},
							{
								province: '新疆',
								name: '图木舒克市',
								area: '西北地区',
								value: 62,
							},
							{
								province: '新疆',
								name: '塔城地区',
								area: '西北地区',
								value: 55,
							},
							{
								province: '新疆',
								name: '巴音郭楞蒙古自治州',
								area: '西北地区',
								value: 20,
							},
							{
								province: '新疆',
								name: '新星市',
								area: '西北地区',
								value: 83,
							},
							{
								province: '新疆',
								name: '昆玉市',
								area: '西北地区',
								value: 84,
							},
							{
								province: '新疆',
								name: '昌吉回族自治州',
								area: '西北地区',
								value: 67,
							},
							{
								province: '新疆',
								name: '石河子市',
								area: '西北地区',
								value: 164,
							},
							{
								province: '新疆',
								name: '胡杨河市',
								area: '西北地区',
								value: 111,
							},
							{
								province: '新疆',
								name: '铁门关市',
								area: '西北地区',
								value: 86,
							},
							{
								province: '新疆',
								name: '阿克苏地区',
								area: '西北地区',
								value: 69,
							},
							{
								province: '新疆',
								name: '阿勒泰地区',
								area: '西北地区',
								value: 14,
							},
							{
								province: '新疆',
								name: '阿拉尔市',
								area: '西北地区',
								value: 113,
							},
						],
					},
					{
						name: '甘肃',
						children: [
							{
								province: '甘肃',
								name: '临夏回族自治州',
								area: '西北地区',
								value: 140,
							},
							{
								province: '甘肃',
								name: '兰州市',
								area: '西北地区',
								value: 148,
							},
							{
								province: '甘肃',
								name: '嘉峪关市',
								area: '西北地区',
								value: 90,
							},
							{
								province: '甘肃',
								name: '天水市',
								area: '西北地区',
								value: 141,
							},
							{
								province: '甘肃',
								name: '定西市',
								area: '西北地区',
								value: 121,
							},
							{
								province: '甘肃',
								name: '平凉市',
								area: '西北地区',
								value: 152,
							},
							{
								province: '甘肃',
								name: '庆阳市',
								area: '西北地区',
								value: 126,
							},
							{
								province: '甘肃',
								name: '张掖市',
								area: '西北地区',
								value: 52,
							},
							{
								province: '甘肃',
								name: '武威市',
								area: '西北地区',
								value: 71,
							},
							{
								province: '甘肃',
								name: '甘南藏族自治州',
								area: '西北地区',
								value: 26,
							},
							{
								province: '甘肃',
								name: '白银市',
								area: '西北地区',
								value: 144,
							},
							{
								province: '甘肃',
								name: '酒泉市',
								area: '西北地区',
								value: 18,
							},
							{
								province: '甘肃',
								name: '金昌市',
								area: '西北地区',
								value: 73,
							},
							{
								province: '甘肃',
								name: '陇南市',
								area: '西北地区',
								value: 114,
							},
						],
					},
				],
			},
			{
				name: '青藏地区',
				children: [
					{
						name: '西藏',
						children: [
							{
								province: '西藏',
								name: '山南市',
								area: '青藏地区',
								value: 25,
							},
							{
								province: '西藏',
								name: '拉萨市',
								area: '青藏地区',
								value: 18,
							},
							{
								province: '西藏',
								name: '日喀则市',
								area: '青藏地区',
								value: 12,
							},
							{
								province: '西藏',
								name: '昌都市',
								area: '青藏地区',
								value: 5,
							},
							{
								province: '西藏',
								name: '林芝市',
								area: '青藏地区',
								value: 12,
							},
							{
								province: '西藏',
								name: '玉树藏族自治州',
								area: '青藏地区',
								value: 3,
							},
							{
								province: '西藏',
								name: '那曲市',
								area: '青藏地区',
								value: 2,
							},
							{
								province: '西藏',
								name: '阿里地区',
								area: '青藏地区',
								value: 4,
							},
						],
					},
					{
						name: '青海',
						children: [
							{
								province: '青海',
								name: '保亭黎族苗族自治县',
								area: '青藏地区',
								value: 61,
							},
							{
								province: '青海',
								name: '吐鲁番市',
								area: '青藏地区',
								value: 74,
							},
							{
								province: '青海',
								name: '果洛藏族自治州',
								area: '青藏地区',
								value: 4,
							},
							{
								province: '青海',
								name: '海东市',
								area: '青藏地区',
								value: 80,
							},
							{
								province: '青海',
								name: '海北藏族自治州',
								area: '青藏地区',
								value: 11,
							},
							{
								province: '青海',
								name: '海南藏族自治州',
								area: '青藏地区',
								value: 5,
							},
							{
								province: '青海',
								name: '海西蒙古族藏族自治州',
								area: '青藏地区',
								value: 5,
							},
							{
								province: '青海',
								name: '西宁市',
								area: '青藏地区',
								value: 66,
							},
							{
								province: '青海',
								name: '黄南藏族自治州',
								area: '青藏地区',
								value: 10,
							},
						],
					},
				],
			},
		],
	});
	const [type, setType] = useState('area');
	const config = {
		data,
		innerRadius: 0.3,
		width: 500,
		height: 500,
		interactions: [
			{
				type: 'element-active',
			},
		],
	};
	const radarData = [
		{
			area: '南方区域',
			province: '上海',
			month: '10',
			value: 0.4068627450980392,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '11',
			value: 0.7990196078431373,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '12',
			value: 0.43137254901960786,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '01',
			value: 0.9705882352941176,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '02',
			value: 0.45588235294117646,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '03',
			value: 0.45098039215686275,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '04',
			value: 0.7794117647058824,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '05',
			value: 0.7254901960784313,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '06',
			value: 0.35294117647058826,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '07',
			value: 0.43137254901960786,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '08',
			value: 0.23529411764705882,
		},
		{
			area: '南方区域',
			province: '上海',
			month: '09',
			value: 0.37745098039215685,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '10',
			value: 4.818627450980392,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '11',
			value: 5.480392156862745,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '12',
			value: 6.004901960784314,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '01',
			value: 6.299019607843137,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '02',
			value: 6.200980392156863,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '03',
			value: 8.514705882352942,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '04',
			value: 7.799019607843137,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '05',
			value: 3.877450980392157,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '06',
			value: 2.985294117647059,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '07',
			value: 4.338235294117647,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '08',
			value: 6.014705882352941,
		},
		{
			area: '南方区域',
			province: '云南',
			month: '09',
			value: 5.686274509803922,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '10',
			value: 10.436363636363636,
		},
		{ area: '西北地区', province: '内蒙古', month: '11', value: 13.2 },
		{
			area: '西北地区',
			province: '内蒙古',
			month: '12',
			value: 17.727272727272727,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '01',
			value: 7.836363636363636,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '02',
			value: 16.927272727272726,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '03',
			value: 22.89090909090909,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '04',
			value: 18.927272727272726,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '05',
			value: 15.963636363636363,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '06',
			value: 12.781818181818181,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '07',
			value: 19.345454545454544,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '08',
			value: 12.563636363636364,
		},
		{
			area: '西北地区',
			province: '内蒙古',
			month: '09',
			value: 11.072727272727272,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '10',
			value: 0.5638297872340425,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '11',
			value: 1.627659574468085,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '12',
			value: 1.127659574468085,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '01',
			value: 0.6276595744680851,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '02',
			value: 1.7765957446808511,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '03',
			value: 1.648936170212766,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '04',
			value: 1.3617021276595744,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '05',
			value: 0.7872340425531915,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '06',
			value: 0.8191489361702128,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '07',
			value: 1.4893617021276595,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '08',
			value: 0.7127659574468085,
		},
		{
			area: '北方区域',
			province: '北京',
			month: '09',
			value: 0.6170212765957447,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '10',
			value: 0.25980392156862747,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '11',
			value: 0.3235294117647059,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '12',
			value: 0.14705882352941177,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '01',
			value: 0.31862745098039214,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '02',
			value: 0.3284313725490196,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '03',
			value: 0.3088235294117647,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '04',
			value: 0.46078431372549017,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '05',
			value: 0.30392156862745096,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '06',
			value: 0.2696078431372549,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '07',
			value: 0.35784313725490197,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '08',
			value: 0.18627450980392157,
		},
		{
			area: '南方区域',
			province: '台湾',
			month: '09',
			value: 0.27941176470588236,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '10',
			value: 4.648936170212766,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '11',
			value: 6.531914893617022,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '12',
			value: 12.127659574468085,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '01',
			value: 8.691489361702128,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '02',
			value: 12.22340425531915,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '03',
			value: 12.585106382978724,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '04',
			value: 7.340425531914893,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '05',
			value: 6.468085106382978,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '06',
			value: 7.053191489361702,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '07',
			value: 7.787234042553192,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '08',
			value: 5.351063829787234,
		},
		{
			area: '北方区域',
			province: '吉林',
			month: '09',
			value: 4.968085106382978,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '10',
			value: 10.637254901960784,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '11',
			value: 13.166666666666666,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '12',
			value: 12.323529411764707,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '01',
			value: 13.098039215686274,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '02',
			value: 13.019607843137255,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '03',
			value: 10.186274509803921,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '04',
			value: 11.735294117647058,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '05',
			value: 10.191176470588236,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '06',
			value: 7.034313725490196,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '07',
			value: 6.666666666666667,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '08',
			value: 10.985294117647058,
		},
		{
			area: '南方区域',
			province: '四川',
			month: '09',
			value: 7.5245098039215685,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '10',
			value: 0.8723404255319149,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '11',
			value: 1.6808510638297873,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '12',
			value: 1.5106382978723405,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '01',
			value: 0.9042553191489362,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '02',
			value: 1.8936170212765957,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '03',
			value: 1.7340425531914894,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '04',
			value: 1.2765957446808511,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '05',
			value: 1.0106382978723405,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '06',
			value: 0.925531914893617,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '07',
			value: 1.4574468085106382,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '08',
			value: 0.8936170212765957,
		},
		{
			area: '北方区域',
			province: '天津',
			month: '09',
			value: 0.7446808510638298,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '10',
			value: 6.963636363636364,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '11',
			value: 11.818181818181818,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '12',
			value: 11.072727272727272,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '01',
			value: 8.036363636363637,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '02',
			value: 7.654545454545454,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '03',
			value: 11.363636363636363,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '04',
			value: 9.854545454545455,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '05',
			value: 7.472727272727273,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '06',
			value: 7.090909090909091,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '07',
			value: 8.345454545454546,
		},
		{
			area: '西北地区',
			province: '宁夏',
			month: '08',
			value: 8.381818181818181,
		},
		{ area: '西北地区', province: '宁夏', month: '09', value: 5.6 },
		{
			area: '南方区域',
			province: '安徽',
			month: '10',
			value: 9.720588235294118,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '11',
			value: 15.07843137254902,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '12',
			value: 10.519607843137255,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '01',
			value: 14.235294117647058,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '02',
			value: 10.235294117647058,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '03',
			value: 11.343137254901961,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '04',
			value: 11.044117647058824,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '05',
			value: 10.647058823529411,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '06',
			value: 6.867647058823529,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '07',
			value: 6.176470588235294,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '08',
			value: 5.431372549019608,
		},
		{
			area: '南方区域',
			province: '安徽',
			month: '09',
			value: 7.769607843137255,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '10',
			value: 15.627659574468085,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '11',
			value: 28.9468085106383,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '12',
			value: 21.69148936170213,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '01',
			value: 26.0531914893617,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '02',
			value: 28.71276595744681,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '03',
			value: 23.127659574468087,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '04',
			value: 25.414893617021278,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '05',
			value: 17.606382978723403,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '06',
			value: 15.170212765957446,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '07',
			value: 16.02127659574468,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '08',
			value: 13.03191489361702,
		},
		{
			area: '北方区域',
			province: '山东',
			month: '09',
			value: 14.053191489361701,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '10',
			value: 10.159574468085106,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '11',
			value: 19.638297872340427,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '12',
			value: 18.361702127659573,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '01',
			value: 11.22340425531915,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '02',
			value: 18.882978723404257,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '03',
			value: 17.04255319148936,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '04',
			value: 15.414893617021276,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '05',
			value: 10.425531914893616,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '06',
			value: 10.446808510638299,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '07',
			value: 14.127659574468085,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '08',
			value: 12.702127659574469,
		},
		{
			area: '北方区域',
			province: '山西',
			month: '09',
			value: 7.25531914893617,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '10',
			value: 8.568627450980392,
		},
		{ area: '南方区域', province: '广东', month: '11', value: 12 },
		{
			area: '南方区域',
			province: '广东',
			month: '12',
			value: 8.642156862745098,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '01',
			value: 7.848039215686274,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '02',
			value: 8.877450980392156,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '03',
			value: 10.568627450980392,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '04',
			value: 10.112745098039216,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '05',
			value: 7.098039215686274,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '06',
			value: 6.284313725490196,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '07',
			value: 5.446078431372549,
		},
		{
			area: '南方区域',
			province: '广东',
			month: '08',
			value: 4.6911764705882355,
		},
		{ area: '南方区域', province: '广东', month: '09', value: 9 },
		{
			area: '南方区域',
			province: '广西',
			month: '10',
			value: 6.078431372549019,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '11',
			value: 9.534313725490197,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '12',
			value: 5.730392156862745,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '01',
			value: 9.450980392156863,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '02',
			value: 7.127450980392157,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '03',
			value: 8.176470588235293,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '04',
			value: 5.985294117647059,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '05',
			value: 4.955882352941177,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '06',
			value: 3.735294117647059,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '07',
			value: 3.5833333333333335,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '08',
			value: 3.911764705882353,
		},
		{
			area: '南方区域',
			province: '广西',
			month: '09',
			value: 5.892156862745098,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '10',
			value: 23.472727272727273,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '11',
			value: 31.90909090909091,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '12',
			value: 30.436363636363637,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '01',
			value: 33.85454545454545,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '02',
			value: 27.98181818181818,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '03',
			value: 24.818181818181817,
		},
		{ area: '西北地区', province: '新疆', month: '04', value: 26 },
		{
			area: '西北地区',
			province: '新疆',
			month: '05',
			value: 41.89090909090909,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '06',
			value: 20.254545454545454,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '07',
			value: 44.90909090909091,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '08',
			value: 25.927272727272726,
		},
		{
			area: '西北地区',
			province: '新疆',
			month: '09',
			value: 38.654545454545456,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '10',
			value: 6.1568627450980395,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '11',
			value: 12.269607843137255,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '12',
			value: 6.740196078431373,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '01',
			value: 12.205882352941176,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '02',
			value: 8.519607843137255,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '03',
			value: 8.558823529411764,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '04',
			value: 10.53921568627451,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '05',
			value: 9.470588235294118,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '06',
			value: 5.651960784313726,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '07',
			value: 5.5931372549019605,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '08',
			value: 4.328431372549019,
		},
		{
			area: '南方区域',
			province: '江苏',
			month: '09',
			value: 6.299019607843137,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '10',
			value: 5.112745098039215,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '11',
			value: 6.9068627450980395,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '12',
			value: 5.431372549019608,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '01',
			value: 8.220588235294118,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '02',
			value: 4.28921568627451,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '03',
			value: 7.112745098039215,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '04',
			value: 5.759803921568627,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '05',
			value: 4.784313725490196,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '06',
			value: 3.3088235294117645,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '07',
			value: 3.911764705882353,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '08',
			value: 2.3529411764705883,
		},
		{
			area: '南方区域',
			province: '江西',
			month: '09',
			value: 4.5931372549019605,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '10',
			value: 10.925531914893616,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '11',
			value: 17.69148936170213,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '12',
			value: 16.03191489361702,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '01',
			value: 12.563829787234043,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '02',
			value: 20.75531914893617,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '03',
			value: 17.638297872340427,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '04',
			value: 14.702127659574469,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '05',
			value: 9.872340425531915,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '06',
			value: 9.53191489361702,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '07',
			value: 14.627659574468085,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '08',
			value: 9.414893617021276,
		},
		{
			area: '北方区域',
			province: '河北',
			month: '09',
			value: 8.138297872340425,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '10',
			value: 27.02127659574468,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '11',
			value: 39.765957446808514,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '12',
			value: 30.680851063829788,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '01',
			value: 26.329787234042552,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '02',
			value: 36.234042553191486,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '03',
			value: 30.06382978723404,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '04',
			value: 26.606382978723403,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '05',
			value: 24.361702127659573,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '06',
			value: 17.819148936170212,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '07',
			value: 16.25531914893617,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '08',
			value: 20.627659574468087,
		},
		{
			area: '北方区域',
			province: '河南',
			month: '09',
			value: 16.24468085106383,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '10',
			value: 5.083333333333333,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '11',
			value: 7.127450980392157,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '12',
			value: 5.28921568627451,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '01',
			value: 8.799019607843137,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '02',
			value: 4.171568627450981,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '03',
			value: 4.78921568627451,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '04',
			value: 6.583333333333333,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '05',
			value: 5.137254901960785,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '06',
			value: 3.465686274509804,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '07',
			value: 4.730392156862745,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '08',
			value: 1.9754901960784315,
		},
		{
			area: '南方区域',
			province: '浙江',
			month: '09',
			value: 4.352941176470588,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '10',
			value: 6.647058823529412,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '11',
			value: 5.9754901960784315,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '12',
			value: 7.348039215686274,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '01',
			value: 5.5588235294117645,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '02',
			value: 5.5588235294117645,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '03',
			value: 5.8088235294117645,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '04',
			value: 5.269607843137255,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '05',
			value: 3.3333333333333335,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '06',
			value: 2.843137254901961,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '07',
			value: 1.6372549019607843,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '08',
			value: 2.480392156862745,
		},
		{
			area: '南方区域',
			province: '海南',
			month: '09',
			value: 7.362745098039215,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '10',
			value: 8.269607843137255,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '11',
			value: 15.230392156862745,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '12',
			value: 10.245098039215685,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '01',
			value: 12.813725490196079,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '02',
			value: 10.573529411764707,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '03',
			value: 12.446078431372548,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '04',
			value: 9.916666666666666,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '05',
			value: 8.127450980392156,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '06',
			value: 5.632352941176471,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '07',
			value: 5.367647058823529,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '08',
			value: 6.382352941176471,
		},
		{
			area: '南方区域',
			province: '湖北',
			month: '09',
			value: 6.936274509803922,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '10',
			value: 6.607843137254902,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '11',
			value: 10.470588235294118,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '12',
			value: 7.519607843137255,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '01',
			value: 11.019607843137255,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '02',
			value: 6.995098039215686,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '03',
			value: 9.32843137254902,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '04',
			value: 6.034313725490196,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '05',
			value: 5.5588235294117645,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '06',
			value: 4.102941176470588,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '07',
			value: 4.328431372549019,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '08',
			value: 4.416666666666667,
		},
		{
			area: '南方区域',
			province: '湖南',
			month: '09',
			value: 5.583333333333333,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '10',
			value: 14.018181818181818,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '11',
			value: 25.745454545454546,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '12',
			value: 27.490909090909092,
		},
		{ area: '西北地区', province: '甘肃', month: '01', value: 21 },
		{
			area: '西北地区',
			province: '甘肃',
			month: '02',
			value: 17.345454545454544,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '03',
			value: 27.345454545454544,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '04',
			value: 24.581818181818182,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '05',
			value: 20.636363636363637,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '06',
			value: 21.945454545454545,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '07',
			value: 21.181818181818183,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '08',
			value: 24.254545454545454,
		},
		{
			area: '西北地区',
			province: '甘肃',
			month: '09',
			value: 14.436363636363636,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '10',
			value: 3.2401960784313726,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '11',
			value: 3.6911764705882355,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '12',
			value: 2.8529411764705883,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '01',
			value: 3.0588235294117645,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '02',
			value: 3.5686274509803924,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '03',
			value: 3.2058823529411766,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '04',
			value: 5.122549019607843,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '05',
			value: 3.284313725490196,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '06',
			value: 3.299019607843137,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '07',
			value: 3.700980392156863,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '08',
			value: 1.5049019607843137,
		},
		{
			area: '南方区域',
			province: '福建',
			month: '09',
			value: 3.2794117647058822,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '10',
			value: 2.588235294117647,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '11',
			value: 4.764705882352941,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '12',
			value: 2.764705882352941,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '01',
			value: 7.411764705882353,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '02',
			value: 4.411764705882353,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '03',
			value: 16.470588235294116,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '04',
			value: 20.529411764705884,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '05',
			value: 18.11764705882353,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '06',
			value: 24.941176470588236,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '07',
			value: 26.823529411764707,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '08',
			value: 23.235294117647058,
		},
		{
			area: '青藏地区',
			province: '西藏',
			month: '09',
			value: 15.823529411764707,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '10',
			value: 3.784313725490196,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '11',
			value: 4.9068627450980395,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '12',
			value: 4.200980392156863,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '01',
			value: 5.9411764705882355,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '02',
			value: 5.142156862745098,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '03',
			value: 4.269607843137255,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '04',
			value: 4.132352941176471,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '05',
			value: 3.607843137254902,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '06',
			value: 2.465686274509804,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '07',
			value: 2.2794117647058822,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '08',
			value: 3.264705882352941,
		},
		{
			area: '南方区域',
			province: '贵州',
			month: '09',
			value: 3.2450980392156863,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '10',
			value: 9.96808510638298,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '11',
			value: 16.06382978723404,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '12',
			value: 18.71276595744681,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '01',
			value: 13.01063829787234,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '02',
			value: 24.01063829787234,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '03',
			value: 20.76595744680851,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '04',
			value: 14.53191489361702,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '05',
			value: 11.26595744680851,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '06',
			value: 11.329787234042554,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '07',
			value: 16.127659574468087,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '08',
			value: 9.946808510638299,
		},
		{
			area: '北方区域',
			province: '辽宁',
			month: '09',
			value: 9.563829787234043,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '10',
			value: 1.2647058823529411,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '11',
			value: 1.5049019607843137,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '12',
			value: 1.2254901960784315,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '01',
			value: 1.3970588235294117,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '02',
			value: 1.3137254901960784,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '03',
			value: 1.0931372549019607,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '04',
			value: 1.0441176470588236,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '05',
			value: 0.9901960784313726,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '06',
			value: 0.6617647058823529,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '07',
			value: 0.5833333333333334,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '08',
			value: 0.8921568627450981,
		},
		{
			area: '南方区域',
			province: '重庆',
			month: '09',
			value: 0.9019607843137255,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '10',
			value: 3.6715686274509802,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '11',
			value: 7.8431372549019605,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '12',
			value: 7.602941176470588,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '01',
			value: 4.470588235294118,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '02',
			value: 5.901960784313726,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '03',
			value: 6.617647058823529,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '04',
			value: 6.0588235294117645,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '05',
			value: 4.7254901960784315,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '06',
			value: 4.348039215686274,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '07',
			value: 4.313725490196078,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '08',
			value: 5.578431372549019,
		},
		{
			area: '南方区域',
			province: '陕西',
			month: '09',
			value: 3.3137254901960786,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '10',
			value: 13.764705882352942,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '11',
			value: 18.58823529411765,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '12',
			value: 19.41176470588235,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '01',
			value: 20.058823529411764,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '02',
			value: 14.647058823529411,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '03',
			value: 34.11764705882353,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '04',
			value: 36.11764705882353,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '05',
			value: 38.705882352941174,
		},
		{ area: '青藏地区', province: '青海', month: '06', value: 43 },
		{
			area: '青藏地区',
			province: '青海',
			month: '07',
			value: 37.88235294117647,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '08',
			value: 42.8235294117647,
		},
		{
			area: '青藏地区',
			province: '青海',
			month: '09',
			value: 27.823529411764707,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '10',
			value: 0.39215686274509803,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '11',
			value: 0.4411764705882353,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '12',
			value: 0.45098039215686275,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '01',
			value: 0.35784313725490197,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '02',
			value: 0.37254901960784315,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '03',
			value: 0.35784313725490197,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '04',
			value: 0.39705882352941174,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '05',
			value: 0.27450980392156865,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '06',
			value: 0.18137254901960784,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '07',
			value: 0.09803921568627451,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '08',
			value: 0.13725490196078433,
		},
		{
			area: '南方区域',
			province: '香港',
			month: '09',
			value: 0.4362745098039216,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '10',
			value: 6.031914893617022,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '11',
			value: 8.212765957446809,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '12',
			value: 8.25531914893617,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '01',
			value: 9.829787234042554,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '02',
			value: 11.553191489361701,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '03',
			value: 13.670212765957446,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '04',
			value: 7.223404255319149,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '05',
			value: 8.680851063829786,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '06',
			value: 8.96808510638298,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '07',
			value: 7.75531914893617,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '08',
			value: 5.8936170212765955,
		},
		{
			area: '北方区域',
			province: '黑龙江',
			month: '09',
			value: 7.159574468085107,
		},
	];
	const dd = getArea(radarData, 'area');

	const [radarConfig, setRadarState] = useState({
		data: dd,
		xField: 'month',
		yField: 'value',
		seriesField: type,
		width: 500,
		height: 500,
		area: {},
		// 开启辅助点
		point: {
			size: 2,
		},
	});
	const ref = useRef(null);
	useEffect(() => {
		const plot = ref.current.getChart();
		console.log(plot);

		plot.on('plot:click', (...args) => {
			const path: string = args[0].data.data.path;
			console.log(path);
			setArea(path);
			setType('province');
			let dd;
			if (!path.includes('区')) {
				dd = getArea(radarData, 'province', path, 'province');
			} else {
				dd = radarData.filter((item) => item.area === path);
			}
			console.log(dd);
			setRadarState({ ...radarConfig, data: dd, seriesField: 'province' });
		});
	}, []);
	return (
		<>
			<div
				style={{
					display: 'flex',
					justifyContent: 'space-around',
					// marginBottom: 200,
				}}
			>
				<div
					style={{
						display: 'flex',
						flexDirection: 'column',
					}}
				>
					<div style={{ textAlign: 'center' }}>AQI分布旭日图</div>
					<Sunburst ref={ref} width={500} {...config} />
				</div>
				<div
					style={{
						display: 'flex',
						flexDirection: 'column',

						// justifyContent: 'space-around',
						// marginBottom: 200,
					}}
				>
					<div style={{ textAlign: 'center' }}>AQI分布雷达图</div>

					<Radar {...radarConfig} />
				</div>
			</div>
		</>
	);
};

export default DemoSunburst;
